# Extracting and Transforming mens batting data

In [1]:
import pandas as pd

In [2]:
import requests
from bs4 import BeautifulSoup

url = 'https://www.cricbuzz.com/cricket-stats/icc-rankings/men/batting'
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')

# Find the desired elements on the page
position1 = soup.find_all('div', class_='cb-col cb-col-16 cb-rank-tbl cb-font-16')
names1 = soup.find_all('a', class_='text-hvr-underline text-bold cb-font-16')
countries1 = soup.find_all('div', class_='cb-font-12 text-gray')
Rating1 = soup.find_all('div', class_='cb-col cb-col-17 cb-rank-tbl pull-right')

positions = []
# Extract the text from the elements
for ptn in position1:
    playerposition = int(ptn.text)
    positions.append(playerposition)

player_names = []
# Extract the text from the elements
for name in names1:
    player_name = name.text
    player_names.append(player_name)
    
country_names = []
# Extract the text from the elements
for country in countries1:
    countree = country.text
    country_names.append(countree)
    
Ratings = []
# Extract the text from the elements
for i in Rating1:
    rati = int(i.text)
    Ratings.append(rati)

In [3]:
ICC_Cricket_Test_Rankings_Mens_Batting = pd.DataFrame({'positions': positions, 'player_names':player_names, 'country_names': country_names, 'Ratings':Ratings})

In [4]:
test_batsmen = ICC_Cricket_Test_Rankings_Mens_Batting.iloc[0:94]
print(test_batsmen.head(10))
print(test_batsmen.tail(10))

   positions        player_names country_names  Ratings
0          1  Marnus Labuschagne     AUSTRALIA      912
1          2        Steven Smith     AUSTRALIA      875
2          3          Babar Azam      PAKISTAN      862
3          4         Travis Head     AUSTRALIA      826
4          5            Joe Root       ENGLAND      814
5          6        Rishabh Pant         INDIA      781
6          7        Rohit Sharma         INDIA      777
7          8     Kane Williamson   NEW ZEALAND      769
8          9  Dimuth Karunaratne     SRI LANKA      748
9         10       Usman Khawaja     AUSTRALIA      746
    positions        player_names country_names  Ratings
84         90     Daniel Lawrence       ENGLAND      363
85         91      Mitchell Starc     AUSTRALIA      361
86         92  Mahmudul Hasan Joy    BANGLADESH      346
87         93     Peter Handscomb     AUSTRALIA      338
88         94        Marco Jansen  SOUTH AFRICA      334
89         95      Shamarh Brooks   WEST INDIES      332
90         96      Keshav Maharaj  SOUTH AFRICA      319
91         98     Donald Tiripano      ZIMBABWE      283
92         99  Mehidy Hasan Miraz    BANGLADESH      283
93        100      Shardul Thakur         INDIA      280

In [5]:
odi_batsmen = ICC_Cricket_Test_Rankings_Mens_Batting.iloc[94:193]
print(odi_batsmen.head(10))
print(odi_batsmen.tail(10))

     positions           player_names country_names  Ratings
94           1             Babar Azam      PAKISTAN      887
95           2  Rassie van der Dussen  SOUTH AFRICA      787
96           3           David Warner     AUSTRALIA      747
97           4        Quinton de Kock  SOUTH AFRICA      743
98           5            Imam-ul-Haq      PAKISTAN      740
99           6           Shubman Gill         INDIA      734
100          7            Virat Kohli         INDIA      727
101          8           Steven Smith     AUSTRALIA      719
102          9           Rohit Sharma         INDIA      719
103         10        Kane Williamson   NEW ZEALAND      700
     positions           player_names         country_names  Ratings
183         91          Cameron Green             AUSTRALIA      429
184         92              Moeen Ali               ENGLAND      429
185         93            Philip Salt               ENGLAND      428
186         94           Aasif Sheikh                 NEPAL      428
187         95           Rishabh Pant                 INDIA      428
188         96  Chundangapoyil Rizwan  UNITED ARAB EMIRATES      427
189         97         Mohammad Usman  UNITED ARAB EMIRATES      427
190         98            Rashid Khan           AFGHANISTAN      426
191         99      Wanindu Hasaranga             SRI LANKA      422
192        100            Kyle Mayers           WEST INDIES      422

In [6]:
t20_batsmen = ICC_Cricket_Test_Rankings_Mens_Batting.iloc[193:]
print(t20_batsmen.head(10))
print(t20_batsmen.tail(10))

     positions      player_names         country_names  Ratings
193          1  Suryakumar Yadav                 INDIA      906
194          2   Mohammad Rizwan              PAKISTAN      836
195          3        Babar Azam              PAKISTAN      778
196          4      Devon Conway           NEW ZEALAND      768
197          5     Aiden Markram          SOUTH AFRICA      748
198          6       Dawid Malan               ENGLAND      719
199          7   Muhammad Waseem  UNITED ARAB EMIRATES      716
200          8     Rilee Rossouw          SOUTH AFRICA      693
201          9       Aaron Finch             AUSTRALIA      680
202         10    Glenn Phillips           NEW ZEALAND      662
     positions         player_names         country_names  Ratings
281         91            Ryan Burl              ZIMBABWE      387
282         92  Dhananjaya de Silva             SRI LANKA      384
283         93         Harry Tector               IRELAND      383
284         94         Rishabh Pant                 INDIA      382
285         95          Usman Ghani           AFGHANISTAN      381
286         96          Chirag Suri  UNITED ARAB EMIRATES      378
287         97      Shimron Hetmyer           WEST INDIES      374
288         98         Norman Vanua      PAPUA NEW GUINEA      371
289         99       Mohammad Usman  UNITED ARAB EMIRATES      364
290        100          Josh Inglis             AUSTRALIA      359

# Extracting and Transforming mens bowling data

In [7]:
import requests
from bs4 import BeautifulSoup

url = 'https://www.cricbuzz.com/cricket-stats/icc-rankings/men/bowling'
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')

# Find the div elements that contain the player positions, names, countries, and ratings
positions2 = soup.find_all('div', class_='cb-col cb-col-16 cb-rank-tbl cb-font-16')
names2 = soup.find_all('a', class_='text-hvr-underline text-bold cb-font-16')
countries2 = soup.find_all('div', class_='cb-font-12 text-gray')
ratings2 = soup.find_all('div', class_='cb-col cb-col-17 cb-rank-tbl pull-right')

# Extract the data from the elements and store it in separate lists
Bowler_positions = []
for ptn in positions2:
    player_position = int(ptn.text)
    Bowler_positions.append(player_position)

Bowler_names = []
for name in names2:
    player_name = name.text
    Bowler_names.append(player_name)

Bowler_country_names = []
for country in countries2:
    country_name = country.text
    Bowler_country_names.append(country_name)

Bowler_ratings = []
for rating in ratings2:
    player_rating = int(rating.text)
    Bowler_ratings.append(player_rating)

In [8]:
ICC_Cricket_Test_Rankings_Mens_Bowling = pd.DataFrame({'Bowler_positions': Bowler_positions, 'Bowler_names':Bowler_names, 'Bowler_country_names': Bowler_country_names, 'Bowler_ratings':Bowler_ratings})

In [9]:
test_bowler = ICC_Cricket_Test_Rankings_Mens_Bowling.iloc[0:89]
print(test_bowler.head(10))
print(test_bowler.tail(10))

   Bowler_positions         Bowler_names Bowler_country_names  Bowler_ratings
0                 1       James Anderson              ENGLAND             866
1                 2  Ravichandran Ashwin                INDIA             864
2                 3          Pat Cummins            AUSTRALIA             858
3                 4       Ollie Robinson              ENGLAND             820
4                 5       Jasprit Bumrah                INDIA             795
5                 6       Shaheen Afridi             PAKISTAN             787
6                 7        Kagiso Rabada         SOUTH AFRICA             776
7                 8        Kyle Jamieson          NEW ZEALAND             765
8                 9      Ravindra Jadeja                INDIA             763
9                10       Mitchell Starc            AUSTRALIA             735
    Bowler_positions          Bowler_names Bowler_country_names  \
79                87     Kraigg Brathwaite          WEST INDIES
80                89           Travis Head            AUSTRALIA
81                90        Shoriful Islam           BANGLADESH
82                92        Angelo Mathews            SRI LANKA
83                93  Wellington Masakadza             ZIMBABWE
84                95       Kane Williamson          NEW ZEALAND
85                96          Jayant Yadav                INDIA
86                97        Jaydev Unadkat                INDIA
87                99    Marnus Labuschagne            AUSTRALIA
88               100            Dean Elgar         SOUTH AFRICA

    Bowler_ratings
79             172
80             142
81             131
82             121
83             111
84             106
85             105
86             102
87              93
88              89

In [10]:
odi_bowler = ICC_Cricket_Test_Rankings_Mens_Bowling.iloc[89:186]
print(odi_bowler.head(10))
print(odi_bowler.tail(10))

    Bowler_positions       Bowler_names Bowler_country_names  Bowler_ratings
89                 1     Mohammed Siraj                INDIA             729
90                 2     Josh Hazlewood            AUSTRALIA             727
91                 3        Trent Boult          NEW ZEALAND             708
92                 4     Mitchell Starc            AUSTRALIA             665
93                 5        Rashid Khan          AFGHANISTAN             659
94                 6         Adam Zampa            AUSTRALIA             655
95                 7    Shakib Al Hasan           BANGLADESH             652
96                 8     Shaheen Afridi             PAKISTAN             641
97                 9  Mustafizur Rahman           BANGLADESH             638
98                10   Mujeeb Ur Rahman          AFGHANISTAN             637
     Bowler_positions          Bowler_names Bowler_country_names  \
176                90            Khawar Ali                 OMAN
177                91           Sean Abbott            AUSTRALIA
178                92           Sompal Kami                NEPAL
179                93        Mitchell Marsh            AUSTRALIA
180                94  Dipendra Singh Airee                NEPAL
181                95        Logan van Beek          NETHERLANDS
182                96         Gulbadin Naib          AFGHANISTAN
183                97     Jeffrey Vandersay            SRI LANKA
184                98            Axar Patel                INDIA
185               100          Jan Frylinck              NAMIBIA

     Bowler_ratings
176             398
177             397
178             397
179             396
180             394
181             394
182             391
183             390
184             380
185             373

In [11]:
t20_bowler = ICC_Cricket_Test_Rankings_Mens_Bowling.iloc[186:]
print(t20_bowler.head(10))
print(t20_bowler.tail(10))

     Bowler_positions       Bowler_names Bowler_country_names  Bowler_ratings
186                 1  Wanindu Hasaranga            SRI LANKA             695
187                 2        Rashid Khan          AFGHANISTAN             694
188                 3        Adil Rashid              ENGLAND             692
189                 4     Josh Hazlewood            AUSTRALIA             690
190                 5         Sam Curran              ENGLAND             688
191                 6     Tabraiz Shamsi         SOUTH AFRICA             681
192                 7         Adam Zampa            AUSTRALIA             678
193                 8      Anrich Nortje         SOUTH AFRICA             659
194                 9   Mitchell Santner          NEW ZEALAND             657
195                10   Mujeeb Ur Rahman          AFGHANISTAN             654
     Bowler_positions    Bowler_names  Bowler_country_names  Bowler_ratings
276                91   Gareth Delany               IRELAND             384
277                92  Barry McCarthy               IRELAND             384
278                93   Sean Williams              ZIMBABWE             383
279                94      Khawar Ali                  OMAN             382
280                95   Rohan Mustafa  UNITED ARAB EMIRATES             382
281                96  Mohammed Shami                 INDIA             382
282                97      Ahmed Raza  UNITED ARAB EMIRATES             381
283                98    Nathan Ellis             AUSTRALIA             380
284                99     Karim Janat           AFGHANISTAN             377
285               100  Abinash Bohara                 NEPAL             374

# Extracting and Transforming mens all rounders data

In [12]:
import requests
from bs4 import BeautifulSoup

url = 'https://www.cricbuzz.com/cricket-stats/icc-rankings/men/all-rounder'
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')

# Find the div elements that contain the player positions, names, countries, and ratings
positions3 = soup.find_all('div', class_='cb-col cb-col-16 cb-rank-tbl cb-font-16')
names3 = soup.find_all('a', class_='text-hvr-underline text-bold cb-font-16')
countries3 = soup.find_all('div', class_='cb-font-12 text-gray')
ratings3 = soup.find_all('div', class_='cb-col cb-col-17 cb-rank-tbl pull-right')

# Extract the data from the elements and store it in separate lists
All_Rounders_positions = []
for ptn in positions3:
    player_position = int(ptn.text)
    All_Rounders_positions.append(player_position)

All_Rounders_names = []
for name in names3:
    player_name = name.text
    All_Rounders_names.append(player_name)

All_Rounders_country_names = []
for country in countries3:
    country_name = country.text
    All_Rounders_country_names.append(country_name)

All_Rounders_ratings = []
for rating in ratings3:
    player_rating = int(rating.text)
    All_Rounders_ratings.append(player_rating)

In [13]:
ICC_Cricket_Test_Rankings_Mens_All_Rounders = pd.DataFrame({'All_Rounders_positions': All_Rounders_positions, 'All_Rounders_names':All_Rounders_names, 'All_Rounders_country_names': All_Rounders_country_names, 'All_Rounders_ratings':All_Rounders_ratings},index=None)

In [14]:
test_allrounder = ICC_Cricket_Test_Rankings_Mens_All_Rounders.iloc[0:10]
test_allrounder

,All_Rounders_positions,All_Rounders_names,All_Rounders_country_names,All_Rounders_ratings
0,1,Ravindra Jadeja,INDIA,460
1,2,Ravichandran Ashwin,INDIA,376
2,3,Shakib Al Hasan,BANGLADESH,329
3,4,Ben Stokes,ENGLAND,320
4,5,Axar Patel,INDIA,283
5,6,Mitchell Starc,AUSTRALIA,265
6,7,Jason Holder,WEST INDIES,264
7,8,Pat Cummins,AUSTRALIA,228
8,9,Kyle Mayers,WEST INDIES,225
9,10,Joe Root,ENGLAND,209

In [15]:
odi_allrounder = ICC_Cricket_Test_Rankings_Mens_All_Rounders.iloc[10:20]
odi_allrounder

,All_Rounders_positions,All_Rounders_names,All_Rounders_country_names,All_Rounders_ratings
10,1,Shakib Al Hasan,BANGLADESH,389
11,2,Mohammad Nabi,AFGHANISTAN,310
12,3,Mehidy Hasan Miraz,BANGLADESH,284
13,4,Rashid Khan,AFGHANISTAN,280
14,5,Mitchell Santner,NEW ZEALAND,269
15,6,Sikandar Raza,ZIMBABWE,253
16,7,Wanindu Hasaranga,SRI LANKA,240
17,8,Zeeshan Maqsood,OMAN,238
18,9,Assad Vala,PAPUA NEW GUINEA,233
19,10,Dhananjaya de Silva,SRI LANKA,221

In [16]:
t20_allrounder = ICC_Cricket_Test_Rankings_Mens_All_Rounders.iloc[20:]
t20_allrounder

,All_Rounders_positions,All_Rounders_names,All_Rounders_country_names,All_Rounders_ratings
20,1,Shakib Al Hasan,BANGLADESH,252
21,2,Hardik Pandya,INDIA,250
22,3,Mohammad Nabi,AFGHANISTAN,219
23,4,Wanindu Hasaranga,SRI LANKA,175
24,5,JJ Smit,NAMIBIA,174
25,6,Sikandar Raza,ZIMBABWE,173
26,7,David Wiese,NAMIBIA,170
27,8,Marcus Stoinis,AUSTRALIA,161
28,9,Moeen Ali,ENGLAND,160
29,10,Glenn Maxwell,AUSTRALIA,160

# Loading Part

In [17]:
output_file1 = r'C:\Users\ashut\Downloads\ICC_Cricket_Test_Rankings_Mens_Batting.csv'

# write the dataframe to a CSV file at the desired location
ICC_Cricket_Test_Rankings_Mens_Batting.to_csv(output_file1, index=False)

In [18]:
output_file2 = r'C:\Users\ashut\Downloads\ICC_Cricket_Test_Rankings_Mens_Bowling.csv'

# write the dataframe to a CSV file at the desired location
ICC_Cricket_Test_Rankings_Mens_Bowling.to_csv(output_file2, index=False)

In [19]:
output_file3 = r'C:\Users\ashut\Downloads\ICC_Cricket_Test_Rankings_Mens_All_Rounders.csv'

# write the dataframe to a CSV file at the desired location
ICC_Cricket_Test_Rankings_Mens_All_Rounders.to_csv(output_file3, index=False)